notify store about application module logic errors
app_module Store with a handler:
```js
Ext.define('App.shoesupro.Store',{
    extend: 'App.store.CRUD',
    requires:[
        'App.store.CRUD'
    ],
    handleStoreException: function handleStoreException(msg){
        l10n._ns = 'so'
        Ext.Msg.show({// handle our own logic error messages
            title: l10n.so.err_title,
            buttons: Ext.Msg.OK,
            icon: Ext.Msg.INFO,
            msg: '<b>' + l10n(msg) + '</b>'
        })
        l10n._ns = ''
    }
})
```